baseURL = 'https://alguidelines.dev/'
enableRobotsTXT = true
languageCode = 'en-us'
title = 'AL Guidelines'

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
author = "author"
category = "categories"
tag = "tags"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"] 

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories", "Authors"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories", "authors"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/blog/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

# Language configuration

[languages]
[languages.en]
description = "Guidelines for when Developing AL for Microsoft Dynamics 365 Business Central"
languageName = "English"
title = "alguidelines.dev - Business Central Design Patterns"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "alguidelines.dev Project"
github_repo = "https://github.com/microsoft/alguidelines"
github_project_repo = "https://github.com/microsoft/alguidelines"
privacy_policy = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "c632b781ffe71b197"
#algolia_docsearch = true

# current release branch - could be rc
release_branch = "master"
# the main version. Never is rc.
release_version = "v1.15.1"

slackurl = ""

installurl = ''
learnmoreurl = ''
#twitterurl = ''

notoc = true

# First one is picked as the Twitter card image if not set on page.
images = ["images/og-image-fission.png"]

[params.social]
#github = ''
#slackurl = ""
#twitter = ''

[[params.whatsnew]]
badge = 'FISSION DZONE REFCARD'
body = 'Get started with Serverless on Kubernetes in 5 minutes! Learn how to set up Fission, its key concepts, how to create and invoke a function, monitor its performance, and more.'
heading = 'New! Download the Fission.io Refcard'
[params.whatsnew.button]
hero_class = 'mid'
text = 'Download Now!'
url = 'https://platform9.com/wp-content/uploads/2019/03/dzone-refcard-fissionio.pdf'

[[params.whatsnew]]
badge = 'BLOG'
body = 'Learn how to use Fission functions with PostgreSQL database.'
heading = 'Fission Functions with PostgreSQL Sample'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'Read More'
url = '/blog/how-to-use-postgresql-database-with-fission-functions/'

[[params.whatsnew]]
badge = 'BLOG'
body = 'Tutorial to deploy Next.js applications with Fission.'
heading = 'Next.js Application with Fission'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'REad More'
url = '/blog/serverless-next.js-example-blog-with-fission/'

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
no = 'Sorry to hear that. Please <a href="https://github.com/microsoft/alguidelines/issues/new">tell us how we can improve</a>.'
yes = 'Glad to hear it! Please <a href="https://github.com/microsoft/alhuidelines/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[[params.links.user]]
desc = "Development takes place here!"
icon = "fab fa-github"
name = "GitHub"
url = "https://github.com/microsoft/alguidelines"
[params.links]
[[params.links.user]]
desc = "Follow us on Twitter to get the latest news!"
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/search?q=%23bcalhelp"
[[params.links.user]]
desc = "Chat with other project users in #users"
icon = "fab fa-discord"
name = "Discord"
url = "https://discord.gg/4wbfNv3"
# End user relevant links. These will show up on left side of footer and in the community page if you have one.


[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[menu]
[[menu.main]]
name = "Docs"
url = "/docs/"
pre = "<i class='fas fa-book'></i>"
weight = 10
[[menu.main]]
name = "Discussions"
url = "https://github.com/microsoft/alguidelines/discussions/"
pre = "<i class='fas fa-comments'></i>"
weight = 11
[[menu.main]]
name = "GitHub"
pre = "<i class='fab fa-github'></i>"
url = "https://github.com/microsoft/alguidelines"
weight = 13
[[menu.main]]
name = "Discord"
pre = "<i class='fab fa-discord'></i>"
url = "https://discord.gg/4wbfNv3"
weight = 14